### ISSUE TITLE
Undefined Variable

### ISSUE THREAD

**Issue by JensSwissCommerce** [boxalino/rtux-shopware#2]
https://github.com/boxalino/rtux-shopware/blob/b95cb7efc93b10e998d2e743022f3364832b81ba/src/Framework/Content/Page/ApiCrossSellingLoaderAjax.php#L108

The variable $blocks is not defined. 

Possible solution:

`        $blocks = $this->getApiResponse()->getBlocks();
          foreach ($blocks as $order => $block) {
...
`

**Comment by dannegwork** [comment]
thanks for reporting.

it`s been fixed.
https://github.com/boxalino/rtux-shopware/commit/cf48a5512eb7cec854504740d02271af2e9208a9
